### ISSUE TITLE
Live streaming support

### ISSUE THREAD

**Issue by yarontorbaty** [brion/ogv.js#158]
I'm trying to implement a streaming service similar to how HLS works.
Segmenting the live source into files of a few seconds each using ffmpeg, then playing them one after the other.
I'm having difficulty catching when one file ends, releasing buffers properly, and using the same Audiocontext for all files.
Any suggestions on where to start?

**Comment by lapierdami** [comment]
Is there an howto on how to implement live streaming?

**Comment by brion** [comment]
On the ogv.js side:
* refactor interfaces to make it possible to append buffers from client code: https://github.com/brion/ogv.js/issues/359

On the client code side:
* either use MSE-compatible interfaces directly, or find and tweak some existing DASH or HLS-via-MSE framework to use the appropriate shim classes instead of native ones

On the server side:
* ???
