### ISSUE TITLE
Demo not working on Chrome Android

### ISSUE THREAD

**Issue by MichelVenatus** [brion/ogv.js#316]
Hi,

after doing some testing with ogv.js on Android I noted some heavy stutter running the 1.0 version. To make sure my modifications did not cause this I tried the demo page and to my surprise it does not work at all, the player never starts when using OGV or WebM.

I tried on this setup:

Chrome 45.0.2454.94
Android 4.4.2
Model - Huawei Honor 6 , PE-TL10

On both WiFi and 4G connections. 

Here is a screenshot of my Chrome Developer Tools, it never goes further than this no matter how long I wait :
![screen shot 2015-10-01 at 12 27 17](https://cloud.githubusercontent.com/assets/12494927/10219561/e0697d0c-6837-11e5-868e-0906ba840e70.png)

I have not experienced the same issue on iOS9, and to have been using ogv.js for some time now it's an issue that seems recent as about a month and a half ago it was running fine.

**Comment by brion** [comment]
Hmm, it's working in Chrome on my Nexus 5 (Android 5.1.1, Chrome 45.0.2454.94)

Ca you check in the network panel, make sure the data's coming through?

**Comment by MichelVenatus** [comment]
Well, interestingly this morning it works fine over WiFi (still not on 4G but I suspect my ISP has some funky stuff going on, not the first time I experience weird behaviours on 4G/3G with video streaming/heavy downloads).

I'll still note that with both OGV 160p and WebM 360p the playback is not smooth and there is an audible audio stutter. How is the playback on the Nexus 5? The Honor 6 is not that bad hardware wise so I'm a bit surprised to see this behaviour.

**Comment by brion** [comment]
I get a little bit of stuttering on the Nexus 5 on .ogv (much more so on the .webm, which is significantly more CPU-intensive).

In general I haven't done more than basic testing on Android though, since it plays back WebM video and Ogg audio natively with much better performance than ogv.js will be able to provide.

Note that there's a HUGE gap in performance on iOS between 32-bit and 64-bit devices, so it'll be interesting to check on newer 64-bit Android devices if there's a significant improvement there as well. I've got a Nexus 5x on order, will test it out when it arrives later this month.
