### ISSUE TITLE
flakiness/video corruption in Chrome 49

### ISSUE THREAD

**Issue by kuro-daei** [brion/ogv.js#328]
Chrome 49.0.2623.87 (64-bit)
Mac 10.11.3 
[screen capture](https://vimeo.com/158441874)

Chrome 48 has no problem.

**Comment by brion** [comment]
Interesting -- if that's it then that's a loooooot easier to fix than a JIT problem. ;) Will double-check the order of events there to make sure I understand what changed.

**Comment by sarang5** [comment]
Came up with the same problem. 
But, what Kuro says is not working in Windows and Android Chrome. 
Only 3-4 times the video is played on out of 10 refreshes. Seems there is no progress(readyState==3) happening for the XHR request being made.

Is it because of the Performance improvement made on Chrome49?

**Comment by sethurajan** [comment]
Hi Brion, Any updates on the issue with Chrome49+? It does not work in Android phones where it uses Chrome browser.

**Comment by brion** [comment]
@sethurajan the one-line patch mentioned above should help; I'll try to test and merge it today or later this week along with some other queued fixes.

**Comment by sethurajan** [comment]
@brion, Thanks for the prompt response. We tried that one-line fix already but the fix is not working consistently as mentioned by @sarang5.
