### ISSUE TITLE
Live Streaming?

### ISSUE THREAD

**Issue by assiomatica** [brion/ogv.js#382]
Please, some example of live streaming.
may be icecast2 and ffmpeg2theora + oggfwd ?

Thank You

Antonio

**Comment by brion** [comment]
Live streaming from a single *non-chained* Ogg stream supplied as a URL ought to work currently, but I have not tested it. If you encounter any problems, please let me know!

[Ogg chaining support](https://github.com/brion/ogv.js/issues/126) for bitstreams that change logical streams has not yet been implemented, but will be needed for adaptive resolution switching in Ogg.

Current plan is also to [add an analogue of the Media Source Extensions interfaces](https://github.com/brion/ogv.js/issues/359), which will allow for doing MPEG-DASH style streaming/switching where buffers are manually loaded via XHR and fed in bit by bit, possibly changing streams due to changing resolution or network conditions.
