### ISSUE TITLE
Seek in Webm doesn't work if cues element is at the end.

### ISSUE THREAD

**Issue by brianxautumn** [brion/ogv.js#432]
On the current nestegg demuxer, seek doesn't work if the cues are located after the clusters. Need to implement on new demuxer.

**Comment by brion** [comment]
It should work on the player, but if this is in your test harness it may require some additional setup.

When the cues are requested for the first time the nestegg-based demuxer tries to seek synchronously on the input stream (which isn't possible in ogv.js, since everything's async!); the demuxer logic catches the error condition and passes an event back to the caller via the 'onseek' property callback with the byte position to seek to.

The caller (OGVPlayer or a test harness) needs to perform the low-level seek and then retry the operation. It's kind of an awkward interface, probably should be abstracted into an 'SeekableInputStream' interface which can be passed into the demuxer instead of the combination of pushing raw input data via a method and letting it request a seek via a callback.

**Comment by brianxautumn** [comment]
Ah, I see, I will look into this.

**Comment by brianxautumn** [comment]
actually on the live demo, I'm getting this:

trying to seek to 12145654
Buffer seek failure in webm demuxer
is seeking processing... MOAR SEEK 12145654 13178471 13178471
SEEKING TO 12145654
failed bq_read len 1 at pos 12145654
out of bytes at start of field
not ready to read the cues

If you are playing a stream, and switch the resolution, it does seek back to the old position though.

**Comment by brion** [comment]
Seems to be an intermittent issue, probably a bug in the i/o adaptor inside the emscripten wrapper around nestegg. Affects some files consistently, others not at all.

**Comment by brion** [comment]
Haven't seen this in a while, hope it's gone? :D Closing out unless seen again on specific files.
