### ISSUE TITLE
Will scrub be a feature?

### ISSUE THREAD

**Issue by brianxautumn** [brion/ogv.js#433]
If not then perhaps only need to trigger a seek for offset at the end of the seek slider drag.

**Comment by brion** [comment]
True scrubbing is tough with the combination of network latency and keyframe distance, though the behavior could be improved with better logic in the control bar on when to cancel and fire off a new seek during the thumb drag. It also should use fastSeek instead of currentTime during drag, which means implementing fastSeek correctly. :)

I suspect really good performance would depend on hacks like you mentioned in email with a pre-extracted sprite of keyframes, which should probably be done one level outside of OGVPlayer (e.g., so you could get the same behavior both when using ogv.js and when using native playback).

The demo harness should be improved though, right now it's kinda ugly and fires off & cancels so many network requests it can be problematic.

**Comment by brion** [comment]
Oh, and fixing the streaming read so it caches some data should help too, allowing faster low-level seeks within data already buffered.

**Comment by brion** [comment]
In latest master the demo's scrubbing should be rather cleaner and friendlier to buffered data. Still not perfect, but better.

* implemented fastSeek to show the first keyframe immediately
* uses fastSeek during scrub
* lets each fastSeek run to completion before triggering the next so it's not constantly aborting and restarting
* does an exact seek on release
