### ISSUE TITLE
Does it/will it ever support .mkv with h264/ac3 on chrome/firefox/IE ?

### ISSUE THREAD

**Issue by albabosh** [brion/ogv.js#446]

**Comment by brion** [comment]
For patent licensing reasoning I'm not likely to include h.264 or aac decoders though they could be plugged in; I suspect a better solution for in-browser playback of such files might be to remux in JavaScript from matroska to fragmented MP4 and feed that into native <video> through media source extensions. That should then work in Chrome, Firefox, and Edge but not older IE.

That's something that would be pretty cool, but won't be on my core agenda.

**Comment by albabosh** [comment]
As I know software panent licensing is not valid in many countries, so is it possible to make a set of non-US plugins ? Is there any info about how to code/compile plugins to ogv.js ?

**Comment by paladox** [comment]
hi please see https://github.com/brion/ogv.js#building-js-components for building ogv.js.

**Comment by brion** [comment]
(Closing out answered questions from issues.)

Related detail issues:
* https://github.com/brion/ogv.js/issues/193 covers adding a module registration API (not yet done).
* https://github.com/brion/ogv.js/issues/192 covers creating a Matroska demuxer plugin that would cover non-WebM variants. (I recommend working from https://github.com/jscodec/jswebm which is a pure-JS version of the WebM demuxer rather than an emscripten C version) This could be shipped with the main distribution, there should be no patent issues.
* https://github.com/brion/ogv.js/issues/190 covers creating an h.264 plugin (not yet done, but should be doable easily with openh264) I can't ship that one compiled but I can happily poke at source. :)
* To cover the requested case, would also need an AC3 audio decoder. Should be doable again, should someone outside want to work on such a one. No idea about suitable libraries to work from.
