### ISSUE TITLE
decoding from binary file to canvas [request] [example]

### ISSUE THREAD

**Issue by ryzed** [brion/ogv.js#447]
It possible to get any example of decoding frame from ArrayBuffer containing video file to canvas or another ArrayBuffer?
Without any streaming, etc.
Thanks.

**Comment by brion** [comment]
If you want to decode and draw some frames rather than playing a video file in the conventional way, you could manually use the underlying decoder classes but BE WARNED they are not public interfaces yet -- internal APIs [will be changed](https://github.com/brion/ogv.js/wiki/Proposed-module-interfaces) when I do more retooling of the library structure to make re-use and plugins easier.

There is a demuxer class, and decoder classes for audio and for video.

Currently the [demuxer class](https://github.com/brion/ogv.js/blob/master/src/js/modules/ogv-demuxer.js) accepts ArrayBuffer data via receiveInput(), and queues up audio and video packets during progressive processing. Each call to process() on the demuxer will churn a bit further through the input, returning true if more input is required before the next packet update. Packets can then be obtained with dequeueVideoPacket() or dequeueAudioPacket().

Individual video packets can then be passed into the [video decoder class](https://github.com/brion/ogv.js/blob/master/src/js/modules/ogv-decoder-video.js) via processHeader() and processFrame() calls. (Theora has 2 header packets which must be decoded first; VP8 has no header packets.) If a frame is successfully processed, the framebuffer property will be filled out with a yuv-buffer object with the decoded frame in YUV format.

You can use the [yuv-canvas](https://github.com/brion/yuv-canvas) class to wrap a canvas and draw the YUV data, with WebGL acceleration if available.

**Comment by brion** [comment]
(closing out answered questions, feel free to reopen if need more help!)
