### ISSUE TITLE
Seeking with currentTime has multi-second error

### ISSUE THREAD

**Issue by Ondross** [brion/ogv.js#449]
Hi—apologies if I am only misusing the library. I am playing Opus files generated with record.js.

I am having a problem with seek precision. In one example, when I set audio.currentTime to 2, it snaps to 0. When I set it to 5, it snaps to 3.64. The same audio file seeks fine with HTML5 audio.

Any tips? Thank you!

**Comment by Ondross** [comment]
As a side note, the reason I'm doing this is because I am faking an actual stream. I am sending real-time ogg/opus chunks to the browser via a websocket.

Because Blobs are read-only, I build a new blob with each new chunk, reset the audio src to the new dataUrl, and seek to the previous position. Is there a better way to append new data with your library?

**Comment by brion** [comment]
Eventually I hope to have a MediaSource API-compatible interface for appending data that's live-streamed or otherwise managed by other sources, but for now that's probably the best way to send in a custom in-memory blob yeah.

If possible can you test if the same file, saved to disk and loaded over a URL, works as expected with ogv.js or if it's experiencing the same 'snapping' behavior? It ought to 'snap' only to the nearest data packet which should be much finer resolution than multi-second, but there might be some oddities in there to fix.

**Comment by Ondross** [comment]
Thanks for the quick response.

Same behavior when loaded from disk. I will start messing with recorder.js settings to see if there might be giant data packets.

I tried setting currentTime from the console in the 7 minutes of terror demo from the readme. It worked as expected (within a tenth of a second.)

**Comment by Ondross** [comment]
[test-audio.txt](https://github.com/brion/ogv.js/files/733382/test-audio.txt)

For reference, here is the file. (github doesn't support uploading .ogg, so I changed the extension).

Sorry in advance for the strange choice of mic check sounds.

**Comment by brion** [comment]
ffprobe shows lots of small packets, but oggz-dump shows only two header packets and no body. Something's weird. :)

Manually grepping in the file I see about 7 total Ogg pages (the 'OggS' marker); not sure how large the individual packets inside are but they seem small enough based on the ffprobe results, assuming those are correct.

It's possible my seeking code is only triggering on the _page_ boundaries, which for an audio-only file with lots of small packets will be much less precise than the actual _packet_ boundaries. (Note that in a video+audio file such as the Curiosity sample, the Ogg bitstream multiplexing must switch streams every 1/24 second or so, which requires a separate page -- so it's got at least the frame rate precision when seeking. In the audio-only case it's possible to combine a lot of small packets into a single page, which looks like is what's being done here, and at a low bitrate that might actually cover multiple seconds.)

I'll see if I can replicate locally (and confirm that the file is behaving as I think it is) and if I can easily fix it...

**Comment by brion** [comment]
Ok, latest master has a fix -- if bisection searching failed to reach sufficient precision it was failing to do a linear seek forward to the time point, leaving us at a page boundary (which for this case was much less precise than on a video+audio file due to that coalescing of multiple packets into a page... Ogg is weird!)

With the fix in, seeks to 2 or 5 seconds seem to come back with the correct found time on your sample file.

Note I haven't pushed a new ogv.js release just yet as I noticed some more bugs still in the stream-file backend code which changed a lot since the last 1.2.x release; want to test a little more before I push out 1.3.0.

This fix should apply cleanly to a release though if you want to copy it in manually. :)

**Comment by Ondross** [comment]
Awesome @brion , thank you so much!
