### ISSUE TITLE
Seeking fails with small opus files

### ISSUE THREAD

**Issue by anonimousse12345** [brion/ogv.js#451]
Hi, while playing back Opus files generated with Recorderjs, I find very short files (with < 1 page of data?) are not able to seek if there is a delay between setting the src and calling play()

Here is an example:
[ogv-playback-bug.zip](https://github.com/brion/ogv.js/files/758582/ogv-playback-bug.zip)

This is on Firefox/Chromium, I don't have access to IE or Safari to test...

(I noticed this when trying to replay an audio by seeking to 0)

**Comment by brion** [comment]
Should work with 1.3.0, which has fixes for seeking within page boundaries.

**Comment by anonimousse12345** [comment]
With 1.3.0, it seems to enter some kind of infinite loop (page freezes up). On Firefox and Chromium.

**Comment by brion** [comment]
Well that's not good. :) I'll investigate shortly...

**Comment by brion** [comment]
So, three problems:
1. it's triggering the seek before we've gone through initial state, instead of after reading headers
2. the bisection seek on indexed Ogg files was not leaving 'space' to sync up the ogg stream if the final page was very long and the file was short
3. the logic in the number 2 case lead to infinite loop instead of error-out

Should have a fix shortly.

**Comment by anonimousse12345** [comment]
Thanks! Works great :-)
