### ISSUE TITLE
Audio sounds tinny when played in the demo VS. browser or outside player. 

### ISSUE THREAD

**Issue by jseward311** [brion/ogv.js#518]
Audio sounds tinny when played in the demo VS. browser or outside player. 

Is there anything I can do to clean up or equalize the raspy voice in this audio file. 
Would switching to opus help?

There is a considerable difference in the volume and tinny sounding voice. 
This happens when just dragging the example file included into the demo player compared to just dragging it into the browser. 

[AudioTinny.zip](https://github.com/brion/ogv.js/files/2984541/AudioTinny.zip)

**Comment by brion** [comment]
I haven't tested yet but I notice the sample file is 8000 Hz; I'm guessing this is due to resampling. Currently the WebAudio output path picks its own sample rate (usually 44100 Hz) and we have to resample any data at other rates, which is done in the AudioFeeder component.

The code doing the resampling is really quick-and-dirty and just does a nearest-neighbor thing, which can produce high-pitch artifacts -- I think this is making the "tinny" sound.

I'll double-check when I'm free later today or tomorrow and make sure that's what's going on. A basic linear interpolation should help, though I'd have to research proper filtering to do much better than that.

**Comment by brion** [comment]
I've added linear interpolation for upsampling but I'm not quite happy with it yet, final output is less tinny but seems to introduce some noise which makes me think I have an off-by-one somewhere.

I also hear what you mean about it being louder than when played directly. Not quite sure what's going on there, will investigate in a bit.

**Comment by brion** [comment]
On the volume issue: currently mono input is upconverted to stereo by duplicating the mono channel data to identical left and right channels. I'm not 100% sure this is correct; possibly it should be reducing the magnitude of each channel by half to keep the total magnitude the same? I'll double-check this and do some more work on making the interpolation right tomorrow.

**Comment by brion** [comment]
Latest commits reduce magnitude by sqrt(2) to maintain loudness on mono -> stereo upconvert, which seems to approximately match what the native playback is doing. Improved interpolation a little more.

It still seems scratchier, which could be a bug in my interpolation or something else.

**Comment by jseward311** [comment]
Awesome. Will test by Monday at the latest.

P.s. also working on a pull request for call back when audioFeeder is
ready. Have this piece working now. Thanks

**Comment by brion** [comment]
I think I worked out that scratchiness from the interpolation -- I wasn't handling packet boundaries correctly so it extended some samples out without interpolation, creating tiny pockets of dead air. Seems better now.

Note this updates the `audio-feeder` dependency so be sure to run `npm install` or `npm ci` to update the dep.

**Comment by brion** [comment]
Note also I left a huge bug in that interpolation, bah. Will fix it in a bit. (pulling from wrong indexes)

**Comment by brion** [comment]
Fixed that last bit.

**Comment by jseward311** [comment]
Verified this fixed audio quality, thanks.
